### ISSUE TITLE
Pair to Pair Code review

### ISSUE THREAD

**Issue by Basir-Mohammadi** [tingamapuro04/Portfolio#5]
Well done you are almost done:
but there are some issues you need to follow.

![Capture](https://user-images.githubusercontent.com/101289027/167085404-a125bcc4-e864-4985-a2ff-45fc175ec602.PNG)

> Reduce the height and width of your container in order to be more responsive.
 

> Add proper HTML semantics

Cheers and happy coding.

**Comment by tingamapuro04** [comment]
Thank you @Basir-Mohammadi
