### ISSUE TITLE
Pair-to-pair code review

### ISSUE THREAD

**Issue by Gleennkar** [tingamapuro04/Portfolio#6]
## Review on the Desktop version of the Portfolio Project
Hi [@tingamapuro04 ](https://github.com/tingamapuro04/) 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
- I will suggest the coder should make proper use of HTML Semantics
-  I will suggest the coder should reduce the height and weight of the container

**Comment by tingamapuro04** [comment]
Thank you @Gleennkar
